[package]
name = "blitz"
description = "High-level APIs for rendering HTML with Blitz"
documentation = "https://docs.rs/blitz"
version = "0.1.0-alpha.5"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/dioxuslabs/blitz"
repository = "https://github.com/dioxuslabs/blitz"
categories = ["web-programming", "gui"]
edition = "2024"
rust-version = "1.85.0"

[features]
default = ["net", "accessibility", "tracing"]
net = ["dep:tokio", "dep:url", "dep:blitz-net"]
accessibility = ["blitz-shell/accessibility"]
tracing = ["blitz-shell/tracing", "blitz-net?/tracing"]

[dependencies]
# Blitz dependencies
anyrender_vello = { path = "../anyrender_vello" }
blitz-traits = { path = "../blitz-traits" }
blitz-dom = { path = "../blitz-dom" }
blitz-html = { path = "../blitz-html" }
blitz-shell = { path = "../blitz-shell" }
blitz-paint = { path = "../blitz-paint" }
blitz-text = { path = "../blitz-text" }
blitz-net = { path = "../blitz-net", optional = true }

# IO & Networking
url = { version = "2.5.7", features = ["serde"], optional = true }
tokio = { version = "1.47.1", features = ["rt-multi-thread", "process"], optional = true }
thiserror = "2.0.16"


[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
