[package]
name = "anyrender_vello"
description = "Vello backend for anyrender"
version = "0.4.1"
homepage = "https://github.com/dioxuslabs/blitz"
repository = "https://github.com/dioxuslabs/blitz"
documentation = "https://docs.rs/anyrender_vello"
license = "MIT OR Apache-2.0"
edition = "2024"
rust-version = "1.85.0"

[features]
log_frame_times = []
debug_text = []

[dependencies]
kurbo = "0.12.0"
peniko = "0.4.1"
raw-window-handle = "0.6.2"
futures-intrusive = "0.5.0"
flume = "0.11.1"
pollster = "0.4.0"
rustc-hash = "2.1.1"
log = "0.4.28"
thiserror = "2.0.16"
glyphon = { git = "https://github.com/cyrup-ai/glyphon", branch = "main" }
blitz-text = { path = "../blitz-text" }
etagere = "0.2"  # Required by glyphon for texture atlas allocation

[dependencies.anyrender]
path = "../anyrender"

[dependencies.vello]
git = "https://github.com/cyrup-ai/vello"
branch = "main"

[dependencies.wgpu]
git = "https://github.com/cyrup-ai/wgpu"
branch = "main"
