[package]
name = "blitz-shell"
description = "Blitz application shell"
documentation = "https://docs.rs/blitz-shell"
version = "0.1.0-alpha.5"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/dioxuslabs/blitz"
repository = "https://github.com/dioxuslabs/blitz"
categories = [ "web-programming", "gui",]
edition = "2024"
rust-version = "1.85.0"

[features]
default = [ "accessibility", "clipboard", "tracing",]
accessibility = [ "dep:accesskit", "dep:accesskit_winit", "blitz-dom/accessibility",]
clipboard = [ "dep:arboard",]
tracing = [ "dep:tracing", "blitz-dom/tracing",]

[dependencies]
winit = "0.30.12"
keyboard-types = "0.8.1"
futures-util = "0.3.31"
flume = "0.11.1"
tokio-util = "0.7.16"

[dependencies.blitz-traits]
path = "../blitz-traits"

[dependencies.blitz-dom]
path = "../blitz-dom"

[dependencies.blitz-paint]
path = "../blitz-paint"

[dependencies.anyrender]
path = "../anyrender"

[dependencies.wgpu]
git = "https://github.com/cyrup-ai/wgpu"
branch = "main"
package = "wgpu"

[dependencies.accesskit]
version = "0.21.0"
optional = true

[dependencies.accesskit_winit]
version = "0.29.0"
optional = true

[dependencies.tracing]
version = "0.1.41"
optional = true

[dependencies.tokio]
version = "1.47.1"
features = [ "rt", "sync", "time", "macros",]



[package.metadata.docs.rs]
all-features = true
rustdoc-args = [ "--cfg", "docsrs",]

[target."cfg(target_os = \"android\")".dependencies.android-activity]
version = "0.6.0"
features = [ "native-activity",]

[target."cfg(any(target_os = \"windows\",target_os = \"macos\",target_os = \"linux\",target_os = \"dragonfly\", target_os = \"freebsd\", target_os = \"netbsd\", target_os = \"openbsd\"))".dependencies.arboard]
version = "3.6.1"
optional = true
