[store]
# Store test results and metadata in the target directory
dir = "target/nextest"

[profile.default]
# Number of tests to run simultaneously
test-threads = "num-cpus"

# Maximum time to wait for tests to finish
slow-timeout = { period = "60s", terminate-after = 2 }

# Retry configuration for flaky tests
retries = 1

# Output configuration
status-level = "pass"
final-status-level = "flaky"

# Test output capture
failure-output = "immediate"
success-output = "never"

# Filter configuration
filter-expr = "not test(test_slow)"

[profile.ci]
# CI-optimized profile
test-threads = 4
retries = 2
slow-timeout = { period = "30s", terminate-after = 1 }
failure-output = "immediate-final"
success-output = "never"

[profile.coverage]
# Coverage profile with detailed output
test-threads = 1
retries = 0
failure-output = "immediate-final"
success-output = "final"