//! Feature creation functions for complex scripts requiring sophisticated shaping

use crate::features::types::FeatureSettings;

/// Create Arabic script features
pub const fn create_arabic_features() -> FeatureSettings {
    FeatureSettings {
        ligatures: true,
        kerning: true,
        contextual_alternates: true,
        stylistic_sets: &[
            1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        ],
        opentype_features: &[
            ("init", 1),
            ("medi", 1),
            ("fina", 1),
            ("isol", 1),
            ("rlig", 1),
            ("liga", 1),
            ("clig", 1),
            ("dlig", 1),
            ("calt", 1),
            ("salt", 1),
            ("swsh", 1),
            ("cswh", 1),
            ("kern", 1),
            ("mark", 1),
            ("mkmk", 1),
            ("curs", 1),
            ("ccmp", 1),
            ("locl", 1),
            ("ss01", 1),
            ("ss02", 1),
            ("ss03", 1),
            ("ss04", 1),
            ("ss05", 1),
            ("ss06", 1),
            ("ss07", 1),
            ("ss08", 1),
            ("ss09", 1),
            ("ss10", 1),
            ("ss11", 1),
            ("ss12", 1),
            ("ss13", 1),
            ("ss14", 1),
            ("ss15", 1),
            ("ss16", 1),
            ("ss17", 1),
            ("ss18", 1),
            ("ss19", 1),
            ("ss20", 1),
        ],
    }
}

/// Create Devanagari script features
pub const fn create_devanagari_features() -> FeatureSettings {
    FeatureSettings {
        ligatures: true,
        kerning: true,
        contextual_alternates: true,
        stylistic_sets: &[
            1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        ],
        opentype_features: &[
            ("nukt", 1),
            ("akhn", 1),
            ("rphf", 1),
            ("blwf", 1),
            ("half", 1),
            ("pstf", 1),
            ("vatu", 1),
            ("cjct", 1),
            ("pres", 1),
            ("abvs", 1),
            ("blws", 1),
            ("psts", 1),
            ("haln", 1),
            ("init", 1),
            ("calt", 1),
            ("liga", 1),
            ("rlig", 1),
            ("ccmp", 1),
            ("locl", 1),
            ("mark", 1),
            ("mkmk", 1),
            ("kern", 1),
            ("dist", 1),
            ("abvm", 1),
            ("blwm", 1),
            ("ss01", 1),
            ("ss02", 1),
            ("ss03", 1),
            ("ss04", 1),
            ("ss05", 1),
            ("ss06", 1),
            ("ss07", 1),
            ("ss08", 1),
            ("ss09", 1),
            ("ss10", 1),
            ("ss11", 1),
            ("ss12", 1),
            ("ss13", 1),
            ("ss14", 1),
            ("ss15", 1),
            ("ss16", 1),
            ("ss17", 1),
            ("ss18", 1),
            ("ss19", 1),
            ("ss20", 1),
        ],
    }
}

/// Create Bengali script features
pub const fn create_bengali_features() -> FeatureSettings {
    FeatureSettings {
        ligatures: true,
        kerning: true,
        contextual_alternates: true,
        stylistic_sets: &[
            1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        ],
        opentype_features: &[
            ("nukt", 1),
            ("akhn", 1),
            ("rphf", 1),
            ("blwf", 1),
            ("half", 1),
            ("pstf", 1),
            ("vatu", 1),
            ("cjct", 1),
            ("init", 1),
            ("pres", 1),
            ("abvs", 1),
            ("blws", 1),
            ("psts", 1),
            ("haln", 1),
            ("calt", 1),
            ("liga", 1),
            ("rlig", 1),
            ("ccmp", 1),
            ("locl", 1),
            ("mark", 1),
            ("mkmk", 1),
            ("kern", 1),
            ("dist", 1),
            ("abvm", 1),
            ("blwm", 1),
            ("ss01", 1),
            ("ss02", 1),
            ("ss03", 1),
            ("ss04", 1),
            ("ss05", 1),
            ("ss06", 1),
            ("ss07", 1),
            ("ss08", 1),
            ("ss09", 1),
            ("ss10", 1),
            ("ss11", 1),
            ("ss12", 1),
            ("ss13", 1),
            ("ss14", 1),
            ("ss15", 1),
            ("ss16", 1),
            ("ss17", 1),
            ("ss18", 1),
            ("ss19", 1),
            ("ss20", 1),
        ],
    }
}

/// Create Thai script features
pub const fn create_thai_features() -> FeatureSettings {
    FeatureSettings {
        ligatures: true,
        kerning: true,
        contextual_alternates: true,
        stylistic_sets: &[
            1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        ],
        opentype_features: &[
            ("ccmp", 1),
            ("mark", 1),
            ("mkmk", 1),
            ("liga", 1),
            ("kern", 1),
            ("calt", 1),
            ("locl", 1),
            ("ss01", 1),
            ("ss02", 1),
            ("ss03", 1),
            ("ss04", 1),
            ("ss05", 1),
            ("ss06", 1),
            ("ss07", 1),
            ("ss08", 1),
            ("ss09", 1),
            ("ss10", 1),
            ("ss11", 1),
            ("ss12", 1),
            ("ss13", 1),
            ("ss14", 1),
            ("ss15", 1),
            ("ss16", 1),
            ("ss17", 1),
            ("ss18", 1),
            ("ss19", 1),
            ("ss20", 1),
        ],
    }
}

/// Create Hebrew script features
pub const fn create_hebrew_features() -> FeatureSettings {
    FeatureSettings {
        ligatures: true,
        kerning: true,
        contextual_alternates: true,
        stylistic_sets: &[
            1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        ],
        opentype_features: &[
            ("kern", 1),
            ("mark", 1),
            ("mkmk", 1),
            ("ccmp", 1),
            ("liga", 1),
            ("dlig", 1),
            ("calt", 1),
            ("locl", 1),
            ("ss01", 1),
            ("ss02", 1),
            ("ss03", 1),
            ("ss04", 1),
            ("ss05", 1),
            ("ss06", 1),
            ("ss07", 1),
            ("ss08", 1),
            ("ss09", 1),
            ("ss10", 1),
            ("ss11", 1),
            ("ss12", 1),
            ("ss13", 1),
            ("ss14", 1),
            ("ss15", 1),
            ("ss16", 1),
            ("ss17", 1),
            ("ss18", 1),
            ("ss19", 1),
            ("ss20", 1),
        ],
    }
}
