[package]
name = "blitz-text"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Advanced text shaping and layout engine for Blitz"

[dependencies]
glyphon = { git = "https://github.com/cyrup-ai/glyphon", branch = "main" }
cosmyc-text = { git = "https://github.com/cyrup-ai/cosmyc-text", branch = "main" }
wgpu = { git = "https://github.com/cyrup-ai/wgpu", branch = "main" }
unicode-bidi = "0.3"
unicode-script = "0.5"
unicode-linebreak = "0.1"
unicode-segmentation = "1.12.0"
bitflags = "2.9.4"
arc-swap = "1.7.1"
once_cell = "1.21.3"
crossbeam = "0.8"
crossbeam-epoch = "0.9.18"
crossbeam-skiplist = "0.1"
crossbeam-utils = "0.8"
crossbeam-channel = "0.5"
ahash = "0.8.12"
ordered-float = "5"
thiserror = "2.0.16"
heapless = "0.9"
ttf-parser = "0.25.1"
parking_lot = "0.12"
image = { version = "0.25.8", default-features = false, features = ["png"] }
thread_local = "1.1.9"
swash = "0.2.5"
log = "0.4"
arrayvec = "0.7.6"
memmap2 = "0.9.8"
lz4_flex = "0.11"
dashmap = "6.1.0"
lru = "0.16.1"
goldylox = { git = "https://github.com/cyrup-ai/goldylox", branch = "main" }
serde = { version = "1.0.226", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
tokio-test = "0.4"

# Nextest configuration  
[package.metadata.nextest]
# Default nextest profile
default-profile = "default"

# Profile configurations
[package.metadata.nextest.profiles.default]
test-threads = 8
retries = 1
fail-fast = false
failure-output = "final"
success-output = "never"

# CI profile for continuous integration
[package.metadata.nextest.profiles.ci]
test-threads = 4  
retries = 3
fail-fast = true
failure-output = "immediate"
success-output = "never"

# Performance profile for benchmarking
[package.metadata.nextest.profiles.perf]
test-threads = 1
retries = 0
fail-fast = true
