[package]
name = "blitz-traits"
description = "Shared traits and types for Blitz"
documentation = "https://docs.rs/blitz-traits"
version = "0.1.0-alpha.5"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/dioxuslabs/blitz"
repository = "https://github.com/dioxuslabs/blitz"
categories = ["web-programming", "gui"]
edition = "2024"
rust-version = "1.85.0"

[dependencies]
http = "1.3.1"
url = "2.5.7"
bytes = "1.10.1"
keyboard-types = "0.8.1"
smol_str = "0.3.2"
bitflags = "2.9.4"
cursor-icon = "1.2.0"
